### ISSUE TITLE
jetbrains/teamcity-agent:2021.1-linux  isn't start because NumberFormatException

### ISSUE THREAD

**Issue by ZotyoNegentropics** [JetBrains/teamcity-docker-images#19]
We upgraded from 2020.2.4 to 2021.1.

Our server has 256GB memory.

Docker version: Docker version 18.06.0-ce, build 0ffa825

We are getting this exception:

```
main method of agent class jetbrains.buildServer.agent.AgentMain2 has failed. null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.agent.AgentMain.main(AgentMain.java:43)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at jdk.internal.platform.Metrics.systemMetrics(Metrics.java:59)
	at jdk.internal.platform.Container.metrics(Container.java:41)
	at sun.management.OperatingSystemImpl.<init>(OperatingSystemImpl.java:46)
	at sun.management.ManagementFactoryHelper.getOperatingSystemMXBean(ManagementFactoryHelper.java:106)
	at java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:374)
	at jetbrains.buildServer.util.DiagnosticUtil.<clinit>(DiagnosticUtil.java:53)
	at jetbrains.buildServer.agent.AgentMain2.main2(AgentMain2.java:68)
	at jetbrains.buildServer.agent.AgentMain2.main(AgentMain2.java:39)
	... 5 more
Caused by: java.lang.NumberFormatException: For input string: "18446744073709551615"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:592)
	at java.lang.Long.parseLong(Long.java:631)
	at jdk.internal.platform.cgroupv1.SubSystem.convertStringToLong(SubSystem.java:159)
	at jdk.internal.platform.cgroupv1.SubSystem.getLongValue(SubSystem.java:153)
	at jdk.internal.platform.cgroupv1.Metrics.getSwapEnabled(Metrics.java:244)
	at jdk.internal.platform.cgroupv1.Metrics.setPath(Metrics.java:230)
	at jdk.internal.platform.cgroupv1.Metrics.setSubSystemPath(Metrics.java:201)
	at jdk.internal.platform.cgroupv1.Metrics.lambda$initContainerSubSystems$5(Metrics.java:121)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at jdk.internal.platform.cgroupv1.Metrics.initContainerSubSystems(Metrics.java:121)
	at jdk.internal.platform.cgroupv1.Metrics.<clinit>(Metrics.java:52)
	... 15 more

```

The agent declaration in the docker compose file:

```
services:
  teamcity-agent-1:
    image: "jetbrains/teamcity-agent:2021.1-linux"
    container_name: teamcity_agent_1
    links:
      - teamcity-server
    environment:
      - "SERVER_URL=http://teamcity-server:8111"
      - "AGENT_NAME=agent-1"
    volumes:
      - teamcity_agent_1_data:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

```

**Comment by ZotyoNegentropics** [comment]
If I use 2.2 version docker file and I configure mem_limit for the agent, it's working...

The modified agent declaration in the docker compose file:

```
version: '2.2'

services:
    teamcity-agent-1:
        image: "jetbrains/teamcity-agent:2021.1-linux"
        container_name: teamcity_agent_1
        mem_limit: 4g
        links:
          - teamcity-server
        environment:
          - "SERVER_URL=http://teamcity-server:8111"
          - "AGENT_NAME=agent-1"
        volumes:
          - teamcity_agent_1_data:/data/teamcity_agent/conf
          - /var/run/docker.sock:/var/run/docker.sock
        restart: always
```

**Comment by ZotyoNegentropics** [comment]
If I use 2.2 version docker compose file and I configure mem_limit for the agent it's working.

Modified agent declaration part from the docker compose file:

```
version: '2.2'

services:

  teamcity-agent-1:
    image: "jetbrains/teamcity-agent:2021.1-linux"
    container_name: teamcity_agent_1
    mem_limit: 4g
    links:
      - teamcity-server
    environment:
      - "SERVER_URL=http://teamcity-server:8111"
      - "AGENT_NAME=agent-1"
    volumes:
      - teamcity_agent_1_data:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
```

**Comment by kir** [comment]
Hi, can I somehow help else? Looks like the issue is solved now.

BTW, I've just updated https://github.com/JetBrains/teamcity-docker-samples/tree/master/compose-ubuntu sample, so you can probably use it a basis.
